//
// Created by YASSINE on 10/10/2021.
//

#ifndef TRAININGPROJECT_PLAYERTYPE_H
#define TRAININGPROJECT_PLAYERTYPE_H

enum PlayerType {
    PASSIVE, AGGRESSIVE
};


#endif //TRAININGPROJECT_PLAYERTYPE_H
